LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_SRC_FILES := fpga.c
LOCAL_CFLAGS := -O3
LOCAL_SHARED_LIBRARIES := libcutils libc
LOCAL_MODULE := fpga.pcm049
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)

include $(BUILD_EXECUTABLE)
